version: "3"

services:
  app:
    build:
      context: ..
      dockerfile:  docker/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../src:/src
    command: >
      sh -c "
      python3 run.py"
    env_file: 
     - .env
